version: "3.9"

services:
  # Flask App Service
  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5000"   # Map local port 5001 to container port 5000
    environment:
      - APP_BASE_URL=${APP_BASE_URL}
      - NWS_BASE_URL=${NWS_BASE_URL}
      - INFLUXDB_HOST_URL=${INFLUXDB_HOST_URL} # Ensure this matches the InfluxDB's URL
      - INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_INIT_ADMIN_TOKEN}
      - INFLUXDB_INIT_ORG=${INFLUXDB_INIT_ORG}
      - INFLUXDB_INIT_BUCKET=${INFLUXDB_INIT_BUCKET}
    restart: always
