version: "3.9"

networks:
  weather-net:
    driver: bridge

services:
  # InfluxDB Service
  influxdb:
    image: influxdb:2.7
    ports:
      - "8086:8086"  # InfluxDB's default port
    volumes:
      - influxdb-storage:/var/lib/influxdb2  # Persist data to avoid data loss
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_INIT_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_INIT_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_INIT_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_INIT_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_INIT_ADMIN_TOKEN}
    restart: always
    networks:
      - weather-net

volumes:
  influxdb-storage:
